# Use the official Python image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .



# Command to run the FastAPI app
#uvicorn main:app --host 0.0.0.0 --port 80
CMD ["uvicorn", "main:app","--host","0.0.0.0","--port","80", "--reload"]
#CMD ["fastapi", "run", "main.py", "--port", "80", "--reload"]

